char *msg_ptr[] = { 
    /*  0 */ "Data on this drive may be|damaged! Please check the|connections and\
 be sure|there is a disk.",
    /*  1 */ "Drive not ready!|Please insert a disk",
    /*  2 */ "The disk in this drive|is write protected",
    /*  3 */ "The original disk has been|removed from the drive",
    /*  4 */ "|This device does not exist",
    /*  5 */ "|This disk contains one|or more bad sectors",
    /*  6 */ "Either Control-C was|pressed or an invalid|function was encountered",
    /*  7 */ "|File not found",
    /*  8 */ "|Path not found",
    /*  9 */ "There are too many|files already open",
    /* 10 */ "Access denied. This is either|a read-only file, a non-empty|\
folder, or an open file",
    /* 11 */ "You do not have enough free|memory for this operation",
    /* 12 */ "This disk drive does|not seem to exist",
    /* 13 */ "This does not seem to be|an executable program",
    /* 14 */ "[1][Version ?.0? of NEOLOAD.PRG|must be present in order for|this \
version of NEODESK.EXE|to run][Abort]",
    /* 15 */ "\033J\r\nApplication exited with status %d",
    /* 16 */ "The redirection file already|exists in read-only mode",
    /* 17 */ "[1][%s|(TOS error #%D)][Ok]",
    /* 18 */ "[1][|TOS error #%D][Ok]",
    /* 19 */ "Could not switch to the|path of this application!",
    /* 20 */ "NEODESK.EXE is either|missing or corrupted!",
    /* 21 */ "\r\n\r\n\033pPress any key or mouse button to return to NeoDesk\033q",
    /* 22 */ "Reloading...",
    /* 23 */ "[3][Could not find NEODESK.EXE|on this disk. Insert a|floppy \
containing that file|into drive %c to continue.][Continue|Quit]",
    /* 24 */ "[Using NeoDesk...",
    /* 25 */ "[1][Incompatible|NEO_INF.DAT file][Sorry]",
    /* 26 */ "[1][The program could|not be opened][Ok]",
    /* 27 */ "by Dan Wilga",
    /* 28 */ "All Rights Reserved.",
    /* 29 */ "Release",
    /* 30 unused */ "",
    /* 31 unused */ "",
    /* 32 unused */ "",
    /* 33 unused */ "",
    /* 34 unused */ "",
    /* 35 */ "[3][This operation requires|more memory than is|permitted in the Memory|\
dialog. Proceed anyway?][Continue|Cancel]",
    /* 36 */ "[1][There is not enough|free memory for this|operation][Cancel]",
    /* 37 */ "" };
