/* Resource file indices for NEODESK. */

#define MMENU            0   /* Menu-tree */
#define NEOTITL          3   /* TITLE in tree MMENU */
#define OPTTITL          6   /* TITLE in tree MMENU */
#define PULL1            8   /* BOX in tree MMENU */
#define ABOUT            9   /* STRING in tree MMENU */
#define OPEN             18  /* STRING in tree MMENU */
#define SHOWINF          19  /* STRING in tree MMENU */
#define QUICKINF         20  /* STRING in tree MMENU */
#define SEARCHDR         21  /* STRING in tree MMENU */
#define DELITEM          22  /* STRING in tree MMENU */
#define FORMAT           24  /* STRING in tree MMENU */
#define PRINTDSK         26  /* STRING in tree MMENU */
#define FORMFEED         27  /* STRING in tree MMENU */
#define QUIT             29  /* STRING in tree MMENU */
#define MPOPMEM          31  /* STRING in tree MMENU */
#define MPOPFILE         32  /* STRING in tree MMENU */
#define MPOPDESK         33  /* STRING in tree MMENU */
#define MPOPWIND         34  /* STRING in tree MMENU */
#define MPOPDIAL         35  /* STRING in tree MMENU */
#define MPOPPATH         36  /* STRING in tree MMENU */
#define MPOPEXT          37  /* STRING in tree MMENU */
#define MPOPINF          38  /* STRING in tree MMENU */
#define MPOPACC          39  /* STRING in tree MMENU */
#define EDITENV          40  /* STRING in tree MMENU */
#define MPOPMISC         41  /* STRING in tree MMENU */
#define MPOPRELD         42  /* STRING in tree MMENU */
#define INSTICON         44  /* STRING in tree MMENU */
#define INSTAPP          45  /* STRING in tree MMENU */
#define PROGINFO         46  /* STRING in tree MMENU */
#define BEMACRO          47  /* STRING in tree MMENU */
#define EXCHMAC          48  /* STRING in tree MMENU */
#define SAVEDESK         50  /* STRING in tree MMENU */
#define LOADINF          51  /* STRING in tree MMENU */
#define EDITICON         53  /* STRING in tree MMENU */
#define SNAPGRID         54  /* STRING in tree MMENU */
#define CHANGREZ         55  /* STRING in tree MMENU */

#define ICONS            1   /* Form/Dialog-box */

#define DESKPAT          2   /* Form/Dialog-box */

#define FILTER           3   /* Form/Dialog-box */
#define FILTEMP          4   /* BUTTON in tree FILTER */
#define FILSIZE          5   /* BUTTON in tree FILTER */
#define FILDATE          6   /* BUTTON in tree FILTER */
#define FILTIME          7   /* BUTTON in tree FILTER */
#define FILATTR          8   /* BUTTON in tree FILTER */
#define FILALL           9   /* BUTTON in tree FILTER */
#define FILGRP           10  /* BUTTON in tree FILTER */
#define FILLOAD          11  /* BUTTON in tree FILTER */
#define FILSAVE          12  /* BUTTON in tree FILTER */
#define FILTM1           13  /* BUTTON in tree FILTER */
#define FILTM1B0         14  /* BUTTON in tree FILTER */
#define FILTM1E0         20  /* FTEXT in tree FILTER */
#define FILTM1X0         26  /* BUTTON in tree FILTER */
#define FILTM2           27  /* BUTTON in tree FILTER */
#define FILTM2B0         28  /* BUTTON in tree FILTER */
#define FILTM2E0         29  /* FTEXT in tree FILTER */
#define FILSIZ           32  /* BUTTON in tree FILTER */
#define FILSIZB0         33  /* BUTTON in tree FILTER */
#define FILSIZE0         36  /* FTEXT in tree FILTER */
#define FILDAT           39  /* BUTTON in tree FILTER */
#define FILDATB0         40  /* BUTTON in tree FILTER */
#define FILDATE0         43  /* FTEXT in tree FILTER */
#define FILDATFM         46  /* STRING in tree FILTER */
#define FILTIM           47  /* BUTTON in tree FILTER */
#define FILTIMB0         48  /* BUTTON in tree FILTER */
#define FILTIME0         51  /* FTEXT in tree FILTER */
#define FILATT           55  /* BUTTON in tree FILTER */
#define FILREAD          56  /* BUTTON in tree FILTER */
#define FILARC           57  /* BUTTON in tree FILTER */
#define FILOK            59  /* BUTTON in tree FILTER */

#define TOSTAKES         4   /* Form/Dialog-box */
#define TOSBOX           3   /* BOX in tree TOSTAKES */
#define TOSEDIT          4   /* FTEXT in tree TOSTAKES */
#define TOSARGV          9   /* BUTTON in tree TOSTAKES */
#define TOSADD           10  /* BUTTON in tree TOSTAKES */
#define TOSOK            12  /* BUTTON in tree TOSTAKES */

#define NEWFOLD          5   /* Form/Dialog-box */
#define FOLDOPEN         3   /* BUTTON in tree NEWFOLD */
#define FOLDEDIT         4   /* FTEXT in tree NEWFOLD */
#define FOLDOK           6   /* BUTTON in tree NEWFOLD */

#define FILEINF          6   /* Form/Dialog-box */
#define FILEEDIT         3   /* FTEXT in tree FILEINF */
#define FILELEN          5   /* STRING in tree FILEINF */
#define FILETIME         7   /* STRING in tree FILEINF */
#define FILESET          8   /* BUTTON in tree FILEINF */
#define FILERO           9   /* BUTTON in tree FILEINF */
#define FILEBOX1         10  /* IBOX in tree FILEINF */
#define FILEFLON         12  /* BUTTON in tree FILEINF */
#define FILEPRVT         14  /* BUTTON in tree FILEINF */
#define FILEGLOB         15  /* BUTTON in tree FILEINF */
#define FILESUP          16  /* BUTTON in tree FILEINF */
#define FILEREAD         17  /* BUTTON in tree FILEINF */
#define FILETTLD         19  /* BUTTON in tree FILEINF */
#define FILETTAL         20  /* BUTTON in tree FILEINF */
#define FILEOK           22  /* BUTTON in tree FILEINF */

#define FOLDINF          7   /* Form/Dialog-box */
#define FOLDNAME         4   /* FTEXT in tree FOLDINF */
#define FOLDTIME         6   /* STRING in tree FOLDINF */
#define FOLDFILE         8   /* STRING in tree FOLDINF */
#define FOLDFOLD         10  /* STRING in tree FOLDINF */
#define FOLDHFIL         12  /* STRING in tree FOLDINF */
#define FOLDHBYT         14  /* STRING in tree FOLDINF */
#define FOLDSIZE         16  /* STRING in tree FOLDINF */
#define FOLDOK2          18  /* BUTTON in tree FOLDINF */
#define FOLDCANC         19  /* BUTTON in tree FOLDINF */

#define DISKINF          8   /* Form/Dialog-box */
#define DISKVOL          4   /* FTEXT in tree DISKINF */
#define DISKFOLD         6   /* STRING in tree DISKINF */
#define DISKFILE         8   /* STRING in tree DISKINF */
#define DISKHFIL         10  /* STRING in tree DISKINF */
#define DISKHBYT         12  /* STRING in tree DISKINF */
#define DISKTOTL         14  /* STRING in tree DISKINF */
#define DISKUSED         16  /* STRING in tree DISKINF */
#define DISKFREE         18  /* STRING in tree DISKINF */
#define DISKSIDE         20  /* STRING in tree DISKINF */
#define DISKSECS         22  /* STRING in tree DISKINF */
#define DISKTPS          24  /* STRING in tree DISKINF */
#define DISKSPT          26  /* STRING in tree DISKINF */
#define DISKBPS          28  /* STRING in tree DISKINF */
#define DISKCLSZ         30  /* STRING in tree DISKINF */
#define DISKOK           32  /* BUTTON in tree DISKINF */

#define INSTALL          9   /* Form/Dialog-box */
#define INLETTER         3   /* FTEXT in tree INSTALL */
#define INSTRING         4   /* FTEXT in tree INSTALL */
#define INVOL            5   /* BUTTON in tree INSTALL */
#define INFLOPPY         6   /* ICON in tree INSTALL */
#define INHARD           7   /* ICON in tree INSTALL */
#define INRAM            8   /* ICON in tree INSTALL */
#define INCLIP           9   /* ICON in tree INSTALL */
#define INPRINT          10  /* ICON in tree INSTALL */
#define INTRASH          11  /* ICON in tree INSTALL */
#define INALL            14  /* BUTTON in tree INSTALL */
#define INCHANGE         16  /* BUTTON in tree INSTALL */
#define INREMOVE         17  /* BUTTON in tree INSTALL */
#define INCANC           18  /* BUTTON in tree INSTALL */

#define ENVIRON          10  /* Form/Dialog-box */
#define ENVBOX           3   /* IBOX in tree ENVIRON */
#define ENVSTR0          4   /* FTEXT in tree ENVIRON */
#define ENVCLICK         14  /* STRING in tree ENVIRON */
#define ENVPARNT         15  /* BUTTON in tree ENVIRON */
#define ENVOK            22  /* BUTTON in tree ENVIRON */

#define FILENAME         11  /* Form/Dialog-box */
#define NAMEEDIT         4   /* FTEXT in tree FILENAME */
#define NAMEOK           5   /* BUTTON in tree FILENAME */
#define NAMEQUIT         7   /* BUTTON in tree FILENAME */

#define APPLIC           12  /* Form/Dialog-box */
#define APPLUP           3   /* BOXCHAR in tree APPLIC */
#define APPLNAME         5   /* BOXTEXT in tree APPLIC */
#define APPLEXTN         6   /* FTEXT in tree APPLIC */
#define APPLDWN          7   /* BOXCHAR in tree APPLIC */
#define APPLPRGT         8   /* BUTTON in tree APPLIC */
#define APPLTOS          9   /* BUTTON in tree APPLIC */
#define APPLGEM          10  /* BUTTON in tree APPLIC */
#define APPLBAT          11  /* BUTTON in tree APPLIC */
#define APPLPARM         12  /* BUTTON in tree APPLIC */
#define APPLNPG          13  /* BUTTON in tree APPLIC */
#define APPLRYES         15  /* BUTTON in tree APPLIC */
#define APPLRNO          16  /* BUTTON in tree APPLIC */
#define APPLRDFT         17  /* BUTTON in tree APPLIC */
#define APPLPPRG         19  /* BUTTON in tree APPLIC */
#define APPLPDOC         20  /* BUTTON in tree APPLIC */
#define APPLINST         22  /* BUTTON in tree APPLIC */
#define APPLREMV         23  /* BUTTON in tree APPLIC */

#define FILECONF         13  /* Form/Dialog-box */
#define FCONSEG          2   /* BUTTON in tree FILECONF */
#define FCONNEW          3   /* FTEXT in tree FILECONF */
#define FCONNAME         5   /* FTEXT in tree FILECONF */
#define FCONOK           8   /* BUTTON in tree FILECONF */
#define FCONSKIP         9   /* BUTTON in tree FILECONF */
#define FCONABRT         10  /* BUTTON in tree FILECONF */

#define FOLDCONF         14  /* Form/Dialog-box */
#define FLDCNEW          3   /* FTEXT in tree FOLDCONF */
#define FLDCNAME         4   /* FTEXT in tree FOLDCONF */
#define FLDCMAKE         6   /* BUTTON in tree FOLDCONF */
#define FLDCUSE          7   /* BUTTON in tree FOLDCONF */

#define COPYMODE         15  /* Form/Dialog-box */
#define CMSOURCE         4   /* STRING in tree COPYMODE */
#define CMDEST           6   /* STRING in tree COPYMODE */
#define CMFILES          7   /* BUTTON in tree COPYMODE */
#define CMFORMAT         8   /* BUTTON in tree COPYMODE */
#define CMNOFMT          9   /* BUTTON in tree COPYMODE */
#define CMFISWAP         13  /* TEXT in tree COPYMODE */
#define CMFOSWAP         17  /* TEXT in tree COPYMODE */
#define CMNOSWAP         21  /* TEXT in tree COPYMODE */
#define CMBACK           22  /* BUTTON in tree COPYMODE */
#define CMCOPIES         23  /* FTEXT in tree COPYMODE */
#define CMOK             25  /* BUTTON in tree COPYMODE */

#define NEWNAME          16  /* Form/Dialog-box */
#define NNPATH           3   /* STRING in tree NEWNAME */
#define NNOLD            4   /* FTEXT in tree NEWNAME */
#define NNNEW            5   /* FTEXT in tree NEWNAME */
#define NNOK             6   /* BUTTON in tree NEWNAME */
#define NNSKIP           7   /* BUTTON in tree NEWNAME */

#define PREFER           17  /* Form/Dialog-box */
#define PREFCYES         3   /* BUTTON in tree PREFER */
#define PREFDYES         4   /* BUTTON in tree PREFER */
#define PREFOYES         5   /* BUTTON in tree PREFER */
#define PREFPYES         6   /* BUTTON in tree PREFER */
#define PREFMYES         7   /* BUTTON in tree PREFER */
#define PREFQYES         8   /* BUTTON in tree PREFER */
#define PREFMCPY         10  /* BUTTON in tree PREFER */
#define PREFMASK         12  /* BUTTON in tree PREFER */
#define MSPRALW          14  /* BUTTON in tree PREFER */
#define PREFBAKS         19  /* BUTTON in tree PREFER */
#define PREFOK           26  /* BUTTON in tree PREFER */

#define MEMORY           18  /* Form/Dialog-box */
#define MEMST            5   /* TEXT in tree MEMORY */
#define MEMTT            7   /* TEXT in tree MEMORY */
#define MEMFREE          8   /* TEXT in tree MEMORY */
#define MEMLARGE         9   /* TEXT in tree MEMORY */
#define MEMROM           10  /* TEXT in tree MEMORY */
#define MEMNEO           12  /* TEXT in tree MEMORY */
#define MEMLIM           13  /* BUTTON in tree MEMORY */
#define MEMTAKE          14  /* BUTTON in tree MEMORY */
#define MEMLKB           16  /* FTEXT in tree MEMORY */
#define MEMTKB           17  /* FTEXT in tree MEMORY */
#define MEMOK            19  /* BUTTON in tree MEMORY */

#define FLFORMAT         19  /* Form/Dialog-box */
#define FLFMTA           4   /* BUTTON in tree FLFORMAT */
#define FLFMTS1          7   /* BUTTON in tree FLFORMAT */
#define FLFMTS2          8   /* BUTTON in tree FLFORMAT */
#define FLFMTS9          10  /* BUTTON in tree FLFORMAT */
#define FLFMT79          13  /* BUTTON in tree FLFORMAT */
#define FLFMTTNO         18  /* BUTTON in tree FLFORMAT */
#define FLFMTTW          19  /* BUTTON in tree FLFORMAT */
#define FLFMT11          20  /* BUTTON in tree FLFORMAT */
#define FLFMTSD          23  /* BUTTON in tree FLFORMAT */
#define FLFMTHD          24  /* BUTTON in tree FLFORMAT */
#define FLFMTXD          25  /* BUTTON in tree FLFORMAT */
#define FLFMTSPC         27  /* BUTTON in tree FLFORMAT */
#define FLFMTUS1         30  /* BOXTEXT in tree FLFORMAT */
#define FLFMTUS2         32  /* BOXTEXT in tree FLFORMAT */
#define FLFMTBAK         34  /* BUTTON in tree FLFORMAT */
#define FLFMTOK          36  /* BUTTON in tree FLFORMAT */

#define GRID             20  /* Form/Dialog-box */
#define SNAPLEFT         3   /* BOXCHAR in tree GRID */
#define SNAPRT           4   /* BOXCHAR in tree GRID */
#define SNAPBOX          5   /* BOX in tree GRID */
#define SNAPI0           6   /* BOX in tree GRID */
#define SNAPUP           10  /* BOXCHAR in tree GRID */
#define SNAPDOWN         11  /* BOXCHAR in tree GRID */
#define SNAPDFLT         12  /* BUTTON in tree GRID */
#define SNAPSORT         13  /* BUTTON in tree GRID */
#define SNAPOVER         15  /* BUTTON in tree GRID */
#define SNAPCLEA         16  /* BUTTON in tree GRID */
#define SNAPOK           17  /* BUTTON in tree GRID */

#define SAVEINF          21  /* Form/Dialog-box */
#define SIDON            3   /* BUTTON in tree SAVEINF */
#define SIDNAM           4   /* FTEXT in tree SAVEINF */
#define SIOK             13  /* BUTTON in tree SAVEINF */

#define PREFPATH         22  /* Form/Dialog-box */
#define PREFBTCH         4   /* FTEXT in tree PREFPATH */
#define PREFAUTO         6   /* FTEXT in tree PREFPATH */
#define PREFTEXT         8   /* FTEXT in tree PREFPATH */
#define PREFPOK          10  /* BUTTON in tree PREFPATH */

#define ACCLIST          23  /* Form/Dialog-box */
#define LISTCLI          4   /* STRING in tree ACCLIST */
#define ACCCLI0          5   /* BUTTON in tree ACCLIST */
#define LISTNAM0         17  /* FTEXT in tree ACCLIST */
#define LISTOK           29  /* BUTTON in tree ACCLIST */

#define INFLIST          24  /* Form/Dialog-box */
#define LISTSIZ0         31  /* STRING in tree INFLIST */
#define INFLOK           43  /* BUTTON in tree INFLIST */

#define EXTENS           25  /* Form/Dialog-box */
#define EXTNUP           3   /* BOXCHAR in tree EXTENS */
#define EXTNNEW          4   /* BUTTON in tree EXTENS */
#define EXTNNAME         5   /* FTEXT in tree EXTENS */
#define EXTNDOWN         6   /* BOXCHAR in tree EXTENS */
#define EXTNDEL          7   /* BUTTON in tree EXTENS */
#define EXTNTOS          9   /* BUTTON in tree EXTENS */
#define EXTNGEM          10  /* BUTTON in tree EXTENS */
#define EXTNBAT          11  /* BUTTON in tree EXTENS */
#define EXTNPARM         12  /* BUTTON in tree EXTENS */
#define EXTNNPG          13  /* BUTTON in tree EXTENS */
#define EXTNOK           15  /* BUTTON in tree EXTENS */

#define DIRPRN           26  /* Form/Dialog-box */
#define PRNSIZ           3   /* BUTTON in tree DIRPRN */
#define PRNDATE          4   /* BUTTON in tree DIRPRN */
#define PRNTIME          5   /* BUTTON in tree DIRPRN */
#define PRNFOLD          6   /* BUTTON in tree DIRPRN */
#define PRNFILE          8   /* BUTTON in tree DIRPRN */
#define PRNPRN           9   /* BUTTON in tree DIRPRN */

#define MACRODEF         27  /* Form/Dialog-box */
#define MACROUP          3   /* BOXCHAR in tree MACRODEF */
#define MACRONAM         4   /* FTEXT in tree MACRODEF */
#define MACRODWN         5   /* BOXCHAR in tree MACRODEF */
#define MACROSIZ         7   /* BOXTEXT in tree MACRODEF */
#define MACROSPC         9   /* BOXTEXT in tree MACRODEF */
#define MACROBOX         10  /* BUTTON in tree MACRODEF */
#define MACRBOX1         11  /* IBOX in tree MACRODEF */
#define MACROCNT         12  /* BUTTON in tree MACRODEF */
#define MACROLSH         13  /* BUTTON in tree MACRODEF */
#define MACRORSH         14  /* BUTTON in tree MACRODEF */
#define MACROALT         15  /* BUTTON in tree MACRODEF */
#define MACRBOX2         16  /* IBOX in tree MACRODEF */
#define MACROKEY         19  /* FTEXT in tree MACRODEF */
#define MACRORKY         20  /* BUTTON in tree MACRODEF */
#define MACROCH          22  /* BUTTON in tree MACRODEF */
#define MACRORMV         23  /* BUTTON in tree MACRODEF */
#define MACRORUN         24  /* BUTTON in tree MACRODEF */

#define TTREZ            28  /* Form/Dialog-box */
#define TTRFBOX          3   /* IBOX in tree TTREZ */
#define FALTC40          5   /* BUTTON in tree TTREZ */
#define FALTC80          6   /* BUTTON in tree TTREZ */
#define FALC2            8   /* BUTTON in tree TTREZ */
#define FALSTL           14  /* BUTTON in tree TTREZ */
#define FALSTM           15  /* BUTTON in tree TTREZ */
#define FALSTH           16  /* BUTTON in tree TTREZ */
#define FALDBL           17  /* BUTTON in tree TTREZ */
#define TTRTTBOX         18  /* IBOX in tree TTREZ */
#define VOSTLOW          19  /* BUTTON in tree TTREZ */
#define TTRINF           25  /* IBOX in tree TTREZ */
#define TTROK            29  /* BUTTON in tree TTREZ */

#define MOREPREF         29  /* Form/Dialog-box */
#define PREFCONS         3   /* BUTTON in tree MOREPREF */
#define MSPRVIR          4   /* BUTTON in tree MOREPREF */
#define MSPRNAM          5   /* BUTTON in tree MOREPREF */
#define MSPRVIEW         6   /* BUTTON in tree MOREPREF */
#define MSPRAV           7   /* BUTTON in tree MOREPREF */
#define MSPRBOX          8   /* BOX in tree MOREPREF */
#define MSPMULT          9   /* BUTTON in tree MOREPREF */
#define MSPRKO           10  /* BUTTON in tree MOREPREF */
#define MSPRNOR          12  /* BUTTON in tree MOREPREF */
#define MSPRDATE         17  /* BUTTON in tree MOREPREF */
#define MSPRDSEP         21  /* FTEXT in tree MOREPREF */
#define MSPRNSHR         23  /* BUTTON in tree MOREPREF */
#define MSPRNLNG         24  /* BUTTON in tree MOREPREF */
#define MSPRNSEP         25  /* FTEXT in tree MOREPREF */
#define PREFSALL         27  /* BUTTON in tree MOREPREF */
#define PREFS0           28  /* BUTTON in tree MOREPREF */
#define MSPROK           31  /* BUTTON in tree MOREPREF */

#define DIALPREF         30  /* Form/Dialog-box */
#define DPRWIND          3   /* BUTTON in tree DIALPREF */
#define DPRLAST          5   /* BUTTON in tree DIALPREF */
#define DPRBUT           8   /* BUTTON in tree DIALPREF */
#define DPROK            10  /* BUTTON in tree DIALPREF */

#define DESKPREF         31  /* Form/Dialog-box */
#define KPRWIND          3   /* BUTTON in tree DESKPREF */
#define KPRBOX           4   /* BUTTON in tree DESKPREF */
#define KPRFILE          5   /* STRING in tree DESKPREF */
#define KPRSEL           6   /* BUTTON in tree DESKPREF */
#define KPRSHOW          7   /* BUTTON in tree DESKPREF */
#define KPRIBOX          8   /* IBOX in tree DESKPREF */
#define KPRCENT          9   /* BUTTON in tree DESKPREF */
#define KPRWALL          10  /* BUTTON in tree DESKPREF */
#define KPROPT           11  /* BUTTON in tree DESKPREF */
#define KPRCALL          13  /* BUTTON in tree DESKPREF */
#define KPRNOTE          16  /* BUTTON in tree DESKPREF */
#define KPROK            18  /* BUTTON in tree DESKPREF */

#define WINPREF          32  /* Form/Dialog-box */
#define WINBOX           3   /* IBOX in tree WINPREF */
#define WPRPSAMP         4   /* BOX in tree WINPREF */
#define WPRSAMP          7   /* BOXTEXT in tree WINPREF */
#define WPRLEFT          8   /* BOXCHAR in tree WINPREF */
#define WPRPAT           9   /* BOXTEXT in tree WINPREF */
#define WPRRT            10  /* BOXCHAR in tree WINPREF */
#define WPROPAQ          17  /* BUTTON in tree WINPREF */
#define WPRICON          19  /* BUTTON in tree WINPREF */
#define WPRFONT          24  /* BUTTON in tree WINPREF */
#define WOPDWN           26  /* BOXCHAR in tree WINPREF */
#define WOPT             27  /* BOXTEXT in tree WINPREF */
#define WOPUP            28  /* BOXCHAR in tree WINPREF */
#define WOPREAL          29  /* BUTTON in tree WINPREF */
#define WOPGAD           30  /* BUTTON in tree WINPREF */
#define WPROK            32  /* BUTTON in tree WINPREF */

#define FILEOP           33  /* Form/Dialog-box */
#define FILESEG          2   /* BUTTON in tree FILEOP */
#define FOSBOX           3   /* BUTTON in tree FILEOP */
#define FOFOLD           5   /* BOXTEXT in tree FILEOP */
#define FOSTAT           6   /* BOXTEXT in tree FILEOP */
#define FOFILES          8   /* BOXTEXT in tree FILEOP */
#define FONAME           9   /* BOXTEXT in tree FILEOP */
#define FOBOX            10  /* IBOX in tree FILEOP */
#define FOOVER           11  /* BUTTON in tree FILEOP */
#define FOCOPY           12  /* BUTTON in tree FILEOP */
#define FOMOVE           13  /* BUTTON in tree FILEOP */
#define FOREN            14  /* BUTTON in tree FILEOP */
#define FOCOUNT          15  /* BUTTON in tree FILEOP */
#define FOFILT           16  /* BUTTON in tree FILEOP */
#define FOBACK           17  /* BUTTON in tree FILEOP */
#define FOEDIT           18  /* BUTTON in tree FILEOP */
#define FOBBOX           19  /* BOX in tree FILEOP */
#define FOOK             20  /* BUTTON in tree FILEOP */
#define FOPAUSE          21  /* BUTTON in tree FILEOP */
#define FOCANC           23  /* BUTTON in tree FILEOP */

#define GRPNAME          34  /* Form/Dialog-box */
#define NGRPNAME         3   /* FTEXT in tree GRPNAME */
#define NGRPWIND         4   /* FTEXT in tree GRPNAME */
#define NGRPDESC         5   /* FTEXT in tree GRPNAME */
#define GRPHIDE          7   /* IBOX in tree GRPNAME */
#define NGRPITEM         8   /* TEXT in tree GRPNAME */
#define NGRPCRE          10  /* STRING in tree GRPNAME */
#define NGRPMOD          12  /* STRING in tree GRPNAME */
#define NGRPOK           14  /* BUTTON in tree GRPNAME */

#define GRPITEM          35  /* Form/Dialog-box */
#define GRPILONG         4   /* STRING in tree GRPITEM */
#define GRPIWIND         5   /* FTEXT in tree GRPITEM */
#define GRPIDESC         6   /* FTEXT in tree GRPITEM */
#define GRPIBOX          8   /* BUTTON in tree GRPITEM */
#define GRPIRKEY         18  /* BUTTON in tree GRPITEM */
#define GRPICKEY         19  /* BUTTON in tree GRPITEM */
#define GRPIOK           21  /* BUTTON in tree GRPITEM */

#define DOPSTAT          36  /* Form/Dialog-box */
#define DOPTYPE          5   /* STRING in tree DOPSTAT */
#define DOPDRIV          6   /* STRING in tree DOPSTAT */
#define DOPSIDE          7   /* STRING in tree DOPSTAT */
#define DOPNUM           8   /* STRING in tree DOPSTAT */
#define DOPSECT          11  /* BOXTEXT in tree DOPSTAT */
#define DOPTRACK         12  /* BOXTEXT in tree DOPSTAT */
#define DOPBAR1          13  /* BOX in tree DOPSTAT */
#define DOPBAR2          16  /* BOX in tree DOPSTAT */
#define DOPBAK           19  /* BUTTON in tree DOPSTAT */
#define DOPPAUSE         21  /* BUTTON in tree DOPSTAT */
#define DOPCANC          22  /* BUTTON in tree DOPSTAT */

#define ENVEDIT          37  /* Form/Dialog-box */
#define ENVESTR          3   /* FTEXT in tree ENVEDIT */
#define ENVEOK           6   /* BUTTON in tree ENVEDIT */

#define EDITNPI          38  /* Form/Dialog-box */
#define NPIPROG          3   /* BUTTON in tree EDITNPI */
#define NPIPATH          4   /* BOXTEXT in tree EDITNPI */
#define NPINAME          5   /* FTEXT in tree EDITNPI */
#define NPIOPT           7   /* BUTTON in tree EDITNPI */
#define NPIMAIN          8   /* BOX in tree EDITNPI */
#define NPIPRGT          9   /* BUTTON in tree EDITNPI */
#define NPITOS           10  /* BUTTON in tree EDITNPI */
#define NPIPARM          13  /* BUTTON in tree EDITNPI */
#define NPINPG           14  /* BUTTON in tree EDITNPI */
#define NPIRYES          16  /* BUTTON in tree EDITNPI */
#define NPIPPRG          20  /* BUTTON in tree EDITNPI */
#define NPIPARMS         22  /* BUTTON in tree EDITNPI */
#define NPIPARM0         23  /* FTEXT in tree EDITNPI */
#define NPIARGV          28  /* BUTTON in tree EDITNPI */
#define NPIMISC          32  /* BUTTON in tree EDITNPI */
#define NPICATT          34  /* BOXCHAR in tree EDITNPI */
#define NPITCHC          39  /* BUTTON in tree EDITNPI */
#define NPISING          41  /* BUTTON in tree EDITNPI */
#define NPIM8HZ          44  /* BUTTON in tree EDITNPI */
#define NPICLK           47  /* BUTTON in tree EDITNPI */
#define NPIBLIT          48  /* BUTTON in tree EDITNPI */
#define NPINEW           50  /* BUTTON in tree EDITNPI */
#define NPISAVE          51  /* BUTTON in tree EDITNPI */

#define NOTEPREF         39  /* Form/Dialog-box */
#define NOTECSAM         3   /* BOX in tree NOTEPREF */
#define NOTESAMP         4   /* BOXTEXT in tree NOTEPREF */
#define NOTLEFT          5   /* BOXCHAR in tree NOTEPREF */
#define NOTECOL          6   /* BOXTEXT in tree NOTEPREF */
#define NOTERT           7   /* BOXCHAR in tree NOTEPREF */
#define NOTEOPAQ         8   /* BUTTON in tree NOTEPREF */
#define NOTEFONT         10  /* BUTTON in tree NOTEPREF */
#define NOTEMI           12  /* BOXCHAR in tree NOTEPREF */
#define NOTEPT           13  /* BOXTEXT in tree NOTEPREF */
#define NOTEPL           14  /* BOXCHAR in tree NOTEPREF */
#define NOTEOK           16  /* BUTTON in tree NOTEPREF */

#define FYI              40  /* Form/Dialog-box */
#define FYISTR1          3   /* TEXT in tree FYI */
#define FYIOK            6   /* BUTTON in tree FYI */

#define PICOPTS          41  /* Form/Dialog-box */
#define PICOFIT          3   /* BUTTON in tree PICOPTS */
#define PICOUNCH         5   /* BUTTON in tree PICOPTS */
#define PICOOK           9   /* BUTTON in tree PICOPTS */

#define IMAGES           42  /* Form/Dialog-box */
#define WDUPLIMG         1   /* IMAGE in tree IMAGES */
#define WMOREUP          2   /* IMAGE in tree IMAGES */
#define WMOREDWN         3   /* IMAGE in tree IMAGES */
#define WI               4   /* IMAGE in tree IMAGES */
#define WT               5   /* IMAGE in tree IMAGES */
#define WSELAL           6   /* IMAGE in tree IMAGES */
#define WPARENT          7   /* IMAGE in tree IMAGES */
#define WTRASH           8   /* IMAGE in tree IMAGES */
#define WCHECK           9   /* IMAGE in tree IMAGES */

#define POPUPS           43  /* Form/Dialog-box */
#define PCOL0            2   /* BOXCHAR in tree POPUPS */
#define PFIL0            19  /* BOXCHAR in tree POPUPS */
#define PNPI0            28  /* STRING in tree POPUPS */

#define WINMENU          44  /* Menu-tree */
#define SORTTITL         5   /* TITLE in tree WINMENU */
#define WIMOPEN          9   /* STRING in tree WINMENU */
#define WIMSHOW          10  /* STRING in tree WINMENU */
#define WIMQUICK         11  /* STRING in tree WINMENU */
#define WIMSRCH          12  /* STRING in tree WINMENU */
#define WIMDEL           13  /* STRING in tree WINMENU */
#define CREATE           15  /* STRING in tree WINMENU */
#define CLOSEFLD         16  /* STRING in tree WINMENU */
#define CLOSEWIN         17  /* STRING in tree WINMENU */
#define SELALL           19  /* STRING in tree WINMENU */
#define WIMGRP           21  /* STRING in tree WINMENU */
#define SHOWICON         23  /* STRING in tree WINMENU */
#define SHOWTEXT         24  /* STRING in tree WINMENU */
#define STLGSML          25  /* STRING in tree WINMENU */
#define STCOLUMN         26  /* STRING in tree WINMENU */
#define STSIZE           27  /* STRING in tree WINMENU */
#define STDATE           28  /* STRING in tree WINMENU */
#define STTIME           29  /* STRING in tree WINMENU */
#define SORTFILT         31  /* STRING in tree WINMENU */
#define PRINTDIR         32  /* STRING in tree WINMENU */
#define UPDATE           34  /* STRING in tree WINMENU */
#define FUPDATE          35  /* STRING in tree WINMENU */
#define SORTNAME         37  /* STRING in tree WINMENU */
#define SORTDATE         38  /* STRING in tree WINMENU */
#define SORTSIZE         39  /* STRING in tree WINMENU */
#define SORTTYPE         40  /* STRING in tree WINMENU */
#define SORTNONE         41  /* STRING in tree WINMENU */
#define REORDER          43  /* STRING in tree WINMENU */
#define WIMAPP           45  /* STRING in tree WINMENU */
#define WIMNPI           46  /* STRING in tree WINMENU */
#define WIMLOAD          47  /* STRING in tree WINMENU */

#define GWINMENU         45  /* Menu-tree */
#define GWIMOPEN         8   /* STRING in tree GWINMENU */
#define GWIMSHOW         9   /* STRING in tree GWINMENU */
#define GWIMCLOS         11  /* STRING in tree GWINMENU */
#define GWIMSEL          13  /* STRING in tree GWINMENU */
#define GWIMDEL          14  /* STRING in tree GWINMENU */
#define GWIMSAVE         16  /* STRING in tree GWINMENU */
#define GWIMICON         18  /* STRING in tree GWINMENU */
#define GWIMTEXT         19  /* STRING in tree GWINMENU */
#define GWIMLGSM         20  /* STRING in tree GWINMENU */
#define GWIMNAME         21  /* STRING in tree GWINMENU */
#define GWIMTYPE         22  /* STRING in tree GWINMENU */
#define GWIMSTYP         23  /* STRING in tree GWINMENU */
#define GWIMSPTH         24  /* STRING in tree GWINMENU */
#define GWIMUPDT         26  /* STRING in tree GWINMENU */
#define GWIMAPP          28  /* STRING in tree GWINMENU */
#define GWIMSNAP         29  /* STRING in tree GWINMENU */
#define GWIMCHNG         30  /* STRING in tree GWINMENU */
#define GWIMLOAD         32  /* STRING in tree GWINMENU */

#define GRIDLOW          46  /* Form/Dialog-box */

#define INSTALOW         47  /* Form/Dialog-box */

#define MMENULOW         48  /* Menu-tree */
