/* Resource File Indices for NEOCNTRL */

#define REZ0OR1  0   /* Form/Dialog */
#define CBOX1    1   /* BOX in tree REZ0OR1 */
#define DATEEDIT 3   /* STRING in tree REZ0OR1 */
#define TIMEEDIT 4   /* STRING in tree REZ0OR1 */
#define SETDT    5   /* BUTTON in tree REZ0OR1 */
#define DATESTR  6   /* STRING in tree REZ0OR1 */
#define TIMEAMPM 8   /* BUTTON in tree REZ0OR1 */
#define TIME24   9   /* BUTTON in tree REZ0OR1 */
#define TIMESTR  10  /* STRING in tree REZ0OR1 */
#define CLOCKSTR 11  /* STRING in tree REZ0OR1 */
#define CLOCKON  13  /* BUTTON in tree REZ0OR1 */
#define CLOCKOFF 14  /* BUTTON in tree REZ0OR1 */
#define CBOX2    15  /* BOX in tree REZ0OR1 */
#define SAVESTR  16  /* STRING in tree REZ0OR1 */
#define SAVERON  18  /* BUTTON in tree REZ0OR1 */
#define SAVEROFF 19  /* BUTTON in tree REZ0OR1 */
#define BLITMSG  20  /* STRING in tree REZ0OR1 */
#define SAVERPL  21  /* BUTTON in tree REZ0OR1 */
#define SAVERMIN 22  /* BOXTEXT in tree REZ0OR1 */
#define SAVERMI  23  /* BUTTON in tree REZ0OR1 */
#define SAVEMSTR 24  /* STRING in tree REZ0OR1 */
#define CBOX4    25  /* BOX in tree REZ0OR1 */
#define REPALEFT 26  /* BOXCHAR in tree REZ0OR1 */
#define REPASLID 27  /* BOX in tree REZ0OR1 */
#define REPADRAG 28  /* BOXCHAR in tree REZ0OR1 */
#define REPART   29  /* BOXCHAR in tree REZ0OR1 */
#define REPAMS   30  /* BOXTEXT in tree REZ0OR1 */
#define REPELEFT 31  /* BOXCHAR in tree REZ0OR1 */
#define REPASTR  36  /* TEXT in tree REZ0OR1 */
#define REPESTR  37  /* TEXT in tree REZ0OR1 */
#define CBOX5    38  /* BOX in tree REZ0OR1 */
#define CLICK    39  /* IMAGE in tree REZ0OR1 */
#define BELL     40  /* IMAGE in tree REZ0OR1 */
#define MOUSEI   41  /* IMAGE in tree REZ0OR1 */
#define PALLETTE 42  /* IMAGE in tree REZ0OR1 */
#define FLOPPYRT 43  /* IMAGE in tree REZ0OR1 */
#define CHIPS    44  /* IMAGE in tree REZ0OR1 */
#define COPYRT   45  /* IMAGE in tree REZ0OR1 */
#define SOUND    46  /* IMAGE in tree REZ0OR1 */
#define CMEMORY  47  /* BOXTEXT in tree REZ0OR1 */

#define EDITDT   1   /* Form/Dialog */
#define EDOK     1   /* BUTTON in tree EDITDT */
#define EDDATE   4   /* FTEXT in tree EDITDT */
#define EDAM     5   /* BUTTON in tree EDITDT */
#define EDPM     6   /* BUTTON in tree EDITDT */
#define EDTIME   7   /* FTEXT in tree EDITDT */

#define CABOUT   2   /* Form/Dialog */

#define MOUSESET 3   /* Form/Dialog */
#define MSSLOW   5   /* BOXCHAR in tree MOUSESET */
#define MSTEST   11  /* BOXTEXT in tree MOUSESET */
#define MSOK     12  /* BUTTON in tree MOUSESET */

#define HIREZ    4   /* Form/Dialog */
#define HBASE    0   /* BOX in tree HIREZ */
#define HBOX1    1   /* BOX in tree HIREZ */
#define HBOX2    2   /* BOX in tree HIREZ */
#define HBOX4    3   /* BOX in tree HIREZ */
#define HBOX5    4   /* BOX in tree HIREZ */
#define HCLICK   5   /* IMAGE in tree HIREZ */
#define HBOX6    13  /* BOXTEXT in tree HIREZ */

#define COLS221  5   /* Form/Dialog */
#define COLSLFT  2   /* BOXCHAR in tree COLS221 */
#define COLSBOX  3   /* BOX in tree COLS221 */
#define COL0     4   /* BOX in tree COLS221 */
#define COLSRT   10  /* BOXCHAR in tree COLS221 */
#define COLNUM   12  /* STRING in tree COLS221 */
#define COLLEFT  15  /* BOXCHAR in tree COLS221 */
#define COLSLID  16  /* BOX in tree COLS221 */
#define COLDRAG  17  /* BOXCHAR in tree COLS221 */
#define COLRT    18  /* BOXCHAR in tree COLS221 */
#define COLRESET 27  /* BUTTON in tree COLS221 */
#define COLQUIT  28  /* BUTTON in tree COLS221 */

#define COLS121  6   /* Form/Dialog */

#define FLOPCFG  7   /* Form/Dialog */
#define FLOPA525 5   /* BUTTON in tree FLOPCFG */
#define FLOPA35  6   /* BUTTON in tree FLOPCFG */
#define FLOPB525 9   /* BUTTON in tree FLOPCFG */
#define FLOPB35  10  /* BUTTON in tree FLOPCFG */
#define FLOPOK   13  /* BUTTON in tree FLOPCFG */

#define CHIPCFG  8   /* Form/Dialog */
#define CHIPBLIT 3   /* BOX in tree CHIPCFG */
#define CHIPMCHC 6   /* BOX in tree CHIPCFG */
#define CHIPM8HZ 9   /* BOXTEXT in tree CHIPCFG */
#define CHIPOK   12  /* BUTTON in tree CHIPCFG */

#define SOUNDCFG 9   /* Form/Dialog */
#define VOLUME   4   /* BOXCHAR in tree SOUNDCFG */
#define VOLNUM   8   /* TEXT in tree SOUNDCFG */
#define BASS     10  /* BOXCHAR in tree SOUNDCFG */
#define TREBLE   16  /* BOXCHAR in tree SOUNDCFG */
#define BALANCE  22  /* BOXCHAR in tree SOUNDCFG */
#define SOUNDTST 27  /* BUTTON in tree SOUNDCFG */
#define SOUNDBOX 28  /* BOX in tree SOUNDCFG */
#define SOUNDCLK 29  /* BOX in tree SOUNDCFG */
#define SOUNDBEL 30  /* BOX in tree SOUNDCFG */
#define SOUNDOK  31  /* BUTTON in tree SOUNDCFG */

#define A3       0   /* Alert String */

#define A5       1   /* Alert String */

#define A6       2   /* Alert String */

#define A7       3   /* Alert String */

#define A8       4   /* Alert String */

#define A10      5   /* Alert String */

#define A12      6   /* Alert String */

#define NOJAR    7   /* Alert String */

#define A1       8   /* Free String */

#define A4       9   /* Free String */

#define A9       10  /* Free String */

#define A11      11  /* Free String */

#define LABEL1   12  /* Free String */

#define LABEL2   13  /* Free String */

#define LABEL3   14  /* Free String */

#define LABEL4   15  /* Free String */

#define LABEL5   16  /* Free String */

#define LABEL6   17  /* Free String */

#define LABEL7   18  /* Free String */

#define LABEL8   19  /* Free String */

#define IDT      20  /* Free String */
