/* Resource File Indices for WINDOWS */

#define DESK     0   /* Form/Dialog */

#define WIND     1   /* Form/Dialog */
#define WCLOSE   1   /* BOXCHAR in tree WIND */
#define WMOVE    2   /* BOXTEXT in tree WIND */
#define WICONIZ  3   /* BOXCHAR in tree WIND */
#define WBACK    4   /* BOXCHAR in tree WIND */
#define WFULL    5   /* BOXCHAR in tree WIND */
#define WILEFT   6   /* BOXCHAR in tree WIND */
#define WINFO    7   /* BOXTEXT in tree WIND */
#define WIRT     8   /* BOXCHAR in tree WIND */
#define WTOOLBOX 9   /* IBOX in tree WIND */
#define WMNLEFT  10  /* BOXCHAR in tree WIND */
#define WMENU    11  /* BOX in tree WIND */
#define WMNRT    12  /* BOXCHAR in tree WIND */
#define WUP      13  /* BOXCHAR in tree WIND */
#define WVBIGSL  14  /* BOX in tree WIND */
#define WVSMLSL  15  /* BOX in tree WIND */
#define WDOWN    16  /* BOXCHAR in tree WIND */
#define WVSPLIT  17  /* BOX in tree WIND */
#define WUP2     18  /* BOXCHAR in tree WIND */
#define WVBIGSL2 19  /* BOX in tree WIND */
#define WVSMLSL2 20  /* BOX in tree WIND */
#define WDOWN2   21  /* BOXCHAR in tree WIND */
#define WLEFT    22  /* BOXCHAR in tree WIND */
#define WHBIGSL  23  /* BOX in tree WIND */
#define WHSMLSL  24  /* BOX in tree WIND */
#define WRT      25  /* BOXCHAR in tree WIND */
#define WHSPLIT  26  /* BOX in tree WIND */
#define WLEFT2   27  /* BOXCHAR in tree WIND */
#define WHBIGSL2 28  /* BOX in tree WIND */
#define WHSMLSL2 29  /* BOX in tree WIND */
#define WRT2     30  /* BOXCHAR in tree WIND */
#define WSIZE    31  /* BOXCHAR in tree WIND */

#define COPYRT   2   /* Form/Dialog */
#define COPMOVE  1   /* BUTTON in tree COPYRT */
#define COPLOGO  2   /* IMAGE in tree COPYRT */
#define COPDATE  7   /* STRING in tree COPYRT */
#define COPNAME  9   /* STRING in tree COPYRT */
#define COPCOMP  10  /* STRING in tree COPYRT */

#define MAGMENU  3   /* Menu Tree */
#define MAGABOUT 8   /* STRING in tree MAGMENU */
#define MAGOPEN  11  /* STRING in tree MAGMENU */
#define MAGQUIT  13  /* STRING in tree MAGMENU */
#define MAGASCII 15  /* STRING in tree MAGMENU */
#define MAGHELP  16  /* STRING in tree MAGMENU */
