/* Resource File Indices for INF_LOAD */

#define MAIN     0   /* Form/Dialog */
#define CPANEL   5   /* BUTTON in tree MAIN */
#define PRINTERQ 6   /* BUTTON in tree MAIN */
#define COLORS   7   /* BUTTON in tree MAIN */
#define SNAPGR   8   /* BUTTON in tree MAIN */
#define PREF     9   /* BUTTON in tree MAIN */
#define AUTOEXC  10  /* BUTTON in tree MAIN */
#define BATCHPRO 11  /* BUTTON in tree MAIN */
#define WINDOWS  12  /* BUTTON in tree MAIN */
#define DTOPICON 13  /* BUTTON in tree MAIN */
#define INSTALAP 14  /* BUTTON in tree MAIN */
#define ENVSTR   15  /* BUTTON in tree MAIN */
#define DFLTPARM 16  /* BUTTON in tree MAIN */
#define CSELALL  17  /* BUTTON in tree MAIN */
#define MINVIS1  18  /* IBOX in tree MAIN */
#define TEMPL    19  /* BUTTON in tree MAIN */
#define PRTDIR   20  /* BUTTON in tree MAIN */
#define FLOP     21  /* BUTTON in tree MAIN */
#define TXTDISP  22  /* BUTTON in tree MAIN */
#define EXTENSS  23  /* BUTTON in tree MAIN */
#define MINVIS2  24  /* IBOX in tree MAIN */
#define DIALOGS  25  /* BUTTON in tree MAIN */
#define MISCSET  26  /* BUTTON in tree MAIN */
#define CPYDELF  27  /* BUTTON in tree MAIN */
#define SRCHFL   28  /* BUTTON in tree MAIN */
#define DESKSET  29  /* BUTTON in tree MAIN */
#define WINDSET  30  /* BUTTON in tree MAIN */
#define DIALSET  31  /* BUTTON in tree MAIN */
#define CONVERT  32  /* BUTTON in tree MAIN */
#define SELINF   33  /* BUTTON in tree MAIN */

#define REZ      1   /* Form/Dialog */
#define REZMED   3   /* BUTTON in tree REZ */
#define REZHIGH  4   /* BUTTON in tree REZ */
#define REZOTH   5   /* BUTTON in tree REZ */
#define OTHWID   6   /* FTEXT in tree REZ */
#define OTHHT    7   /* FTEXT in tree REZ */
#define OTHCONV  8   /* BUTTON in tree REZ */

#define CINFO    2   /* Form/Dialog */

#define A1       0   /* Alert String */

#define A2       1   /* Alert String */

#define A4       2   /* Alert String */

#define A5       3   /* Alert String */

#define A6       4   /* Alert String */

#define A3       5   /* Alert String */

#define BADNEO   6   /* Alert String */

#define NOTMULTI 7   /* Alert String */

#define NOWINDS  8   /* Alert String */

#define A7       9   /* Free String */

#define A8       10  /* Free String */
