/* Resource File Indices for NEOQ_M */

#define FORM1    0   /* Form/Dialog */

#define FORM2    1   /* Form/Dialog */

#define INFORM   2   /* Form/Dialog */

#define A1       0   /* Alert String */

#define A2       1   /* Alert String */

#define A4       2   /* Alert String */

#define A5       3   /* Alert String */

#define A6       4   /* Alert String */

#define A8       5   /* Alert String */

#define A10      6   /* Alert String */

#define A11      7   /* Alert String */

#define A12      8   /* Alert String */

#define A14      9   /* Alert String */

#define A15      10  /* Alert String */

#define A16      11  /* Alert String */

#define A7       12  /* Free String */

#define A13      13  /* Free String */

#define EXTDATA  14  /* Free String */
