/* Resource File Indices for NEOQ_C */

#define QUEUE    0   /* Form/Dialog */
#define QBOX     1   /* BOX in tree QUEUE */
#define QLEFT    2   /* BOXCHAR in tree QUEUE */
#define QBIG     3   /* BOX in tree QUEUE */
#define QSMALL   4   /* BOX in tree QUEUE */
#define QRIGHT   5   /* BOXCHAR in tree QUEUE */
#define QTRASH   7   /* ICON in tree QUEUE */
#define QPRNCNFG 8   /* BUTTON in tree QUEUE */
#define QFILES   9   /* BUTTON in tree QUEUE */
#define QFFD     10  /* BUTTON in tree QUEUE */
#define COPYRT   11  /* BOXCHAR in tree QUEUE */

#define PRNCNFG  1   /* Form/Dialog */
#define PRNBUT0  4   /* BUTTON in tree PRNCNFG */
#define PRNFFD   28  /* BUTTON in tree PRNCNFG */
#define PRNQOK   30  /* BUTTON in tree PRNCNFG */

#define INFORM   2   /* Form/Dialog */

#define A1       0   /* Alert String */

#define A2       1   /* Alert String */

#define A4       2   /* Alert String */

#define A5       3   /* Alert String */

#define A6       4   /* Alert String */

#define A8       5   /* Alert String */

#define A10      6   /* Alert String */

#define A11      7   /* Alert String */

#define A12      8   /* Alert String */

#define A14      9   /* Alert String */

#define A15      10  /* Alert String */

#define A16      11  /* Alert String */

#define A7       12  /* Free String */

#define A13      13  /* Free String */

#define EXTDATA  14  /* Free String */
