/* Resource File Indices for TRASHCAN */

#define MAIN     0   /* Form/Dialog */
#define FILESTR  5   /* BOXTEXT in tree MAIN */
#define NAMEBOX  6   /* BOX in tree MAIN */
#define NAME0    7   /* BOXTEXT in tree MAIN */
#define NAMEBOX2 17  /* BOX in tree MAIN */
#define DATE0    18  /* TEXT in tree MAIN */
#define UP       28  /* BOXCHAR in tree MAIN */
#define BIGSL    29  /* BOX in tree MAIN */
#define SMLSL    30  /* BOX in tree MAIN */
#define CONFON   31  /* BUTTON in tree MAIN */
#define DRIVEA   34  /* BOXCHAR in tree MAIN */
#define DOWN     60  /* BOXCHAR in tree MAIN */
#define LEFT     61  /* BOXCHAR in tree MAIN */
#define BIGSLH   62  /* BOX in tree MAIN */
#define SMLSLH   63  /* BOX in tree MAIN */
#define RIGHT    64  /* BOXCHAR in tree MAIN */
#define DTSD     65  /* BOXCHAR in tree MAIN */
#define DTST     66  /* BOXCHAR in tree MAIN */
#define DTSS     67  /* BOXCHAR in tree MAIN */
#define WARN     69  /* BUTTON in tree MAIN */
#define SELALL   70  /* BUTTON in tree MAIN */
#define UNDEL    71  /* BUTTON in tree MAIN */
#define DELPERM  72  /* BUTTON in tree MAIN */
#define GETINFO  73  /* BUTTON in tree MAIN */
#define QUIT     74  /* BUTTON in tree MAIN */

#define INFO1    1   /* Form/Dialog */

#define CONFL    2   /* Form/Dialog */
#define CONFORIG 3   /* FTEXT in tree CONFL */
#define CONFNEW  4   /* FTEXT in tree CONFL */
#define NEWNAME  5   /* BUTTON in tree CONFL */
#define CONFSKIP 6   /* BUTTON in tree CONFL */

#define WARNINGS 3   /* Form/Dialog */

#define BADNEO   0   /* Alert String */

#define DELPER   1   /* Alert String */

#define DELTEMP  2   /* Alert String */

#define MOREITMS 3   /* Alert String */

#define A1       4   /* Alert String */

#define A2       5   /* Alert String */

#define A3       6   /* Alert String */

#define A4       7   /* Alert String */

#define A5       8   /* Alert String */

#define A6       9   /* Alert String */

#define A7       10  /* Alert String */

#define A8       11  /* Alert String */

#define A9       12  /* Alert String */

#define A10      13  /* Alert String */

#define A11      14  /* Alert String */

#define A12      15  /* Alert String */

#define A13      16  /* Alert String */

#define A15      17  /* Alert String */

#define A16      18  /* Alert String */

#define A17      19  /* Alert String */

#define A18      20  /* Alert String */

#define A19      21  /* Alert String */

#define A20      22  /* Alert String */

#define A22      23  /* Alert String */

#define A23      24  /* Alert String */

#define A24      25  /* Alert String */

#define BADREZ   26  /* Alert String */

#define ACCNAME  27  /* Free String */
