/* Resource File Indices for HELP */

#define HMENU    0   /* Menu Tree */
#define TFILE    3   /* TITLE in tree HMENU */
#define TTOPIC   4   /* TITLE in tree HMENU */
#define TSET     5   /* TITLE in tree HMENU */
#define MHELP    8   /* STRING in tree HMENU */
#define MHPATH   9   /* STRING in tree HMENU */
#define MCLIP    11  /* STRING in tree HMENU */
#define MTEXT    12  /* STRING in tree HMENU */
#define MBLOCK   13  /* STRING in tree HMENU */
#define MQUIT    15  /* STRING in tree HMENU */
#define MFIND    17  /* STRING in tree HMENU */
#define MINDEX   18  /* STRING in tree HMENU */
#define MPREV    19  /* STRING in tree HMENU */
#define MUSING   21  /* STRING in tree HMENU */
#define MFONT    23  /* STRING in tree HMENU */

#define FIND     1   /* Form/Dialog */
#define FTOPIC   3   /* FTEXT in tree FIND */
#define FMATCH   5   /* BUTTON in tree FIND */
#define FALL     6   /* BUTTON in tree FIND */
#define FOK      7   /* BUTTON in tree FIND */

#define WINDOPTS 2   /* Form/Dialog */
#define FOSAMP   3   /* BUTTON in tree WINDOPTS */
#define FOSAMP1  4   /* TEXT in tree WINDOPTS */
#define FOFONT   9   /* BUTTON in tree WINDOPTS */
#define FOPDWN   13  /* BOXCHAR in tree WINDOPTS */
#define FOPT     14  /* BUTTON in tree WINDOPTS */
#define FOPUP    15  /* BOXCHAR in tree WINDOPTS */
#define FOOK     16  /* BUTTON in tree WINDOPTS */
#define FOCANC   17  /* BUTTON in tree WINDOPTS */

#define MODAL    3   /* Form/Dialog */
#define MMOVE    1   /* BUTTON in tree MODAL */
#define MTITLE   2   /* BUTTON in tree MODAL */
#define MFILE    3   /* BUTTON in tree MODAL */
#define MTOPIC   4   /* BUTTON in tree MODAL */
#define MSET     5   /* BUTTON in tree MODAL */
#define MOQUIT   6   /* BUTTON in tree MODAL */
#define MOPREV   7   /* BUTTON in tree MODAL */
#define MSTAT    8   /* BOXTEXT in tree MODAL */
#define MBOX     9   /* IBOX in tree MODAL */
#define MDISP    10  /* USERDEF in tree MODAL */
#define UP       11  /* BOXCHAR in tree MODAL */
#define BIGSL    12  /* BOX in tree MODAL */
#define SMLSL    13  /* BOX in tree MODAL */
#define DOWN     14  /* BOXCHAR in tree MODAL */
#define LEFT     15  /* BOXCHAR in tree MODAL */
#define BIGSLH   16  /* BOX in tree MODAL */
#define SMLSLH   17  /* BOX in tree MODAL */
#define RIGHT    18  /* BOXCHAR in tree MODAL */
#define MBLANK   19  /* BOX in tree MODAL */

#define READERR  0   /* Alert String */

#define ALNOMEM  1   /* Alert String */

#define ALNOTOP  2   /* Alert String */

#define ALMEMHLP 3   /* Alert String */

#define ALNOTHLP 4   /* Alert String */

#define ALOPEN   5   /* Alert String */

#define ALVDI    6   /* Alert String */

#define NOCREAT  7   /* Alert String */

#define NOWRITE  8   /* Alert String */

#define BADCLIP  9   /* Alert String */

#define EMPLINE  10  /* Free String */

#define EMPLINE2 11  /* Free String */

#define EMPLINE3 12  /* Free String */

#define EMPLINE4 13  /* Free String */

#define EMPLINE5 14  /* Free String */

#define INDEX    15  /* Free String */

#define HELPTITL 16  /* Free String */

#define SYSTEM   17  /* Free String */

#define HELPSTR  18  /* Free String */

#define HELPPATH 19  /* Free String */

#define SAVEPATH 20  /* Free String */

#define TITLE    21  /* Free String */
