/* Resource file indices for ICONEDIT. */

#define IMENU            0   /* Menu-tree */
#define IABOUT           8   /* STRING in tree IMENU */
#define IOPEN            17  /* STRING in tree IMENU */
#define ISHOW            18  /* STRING in tree IMENU */
#define IQUIT            20  /* STRING in tree IMENU */
#define IEDITPAT         22  /* STRING in tree IMENU */
#define IRESETI          23  /* STRING in tree IMENU */
#define ISHRINK          24  /* STRING in tree IMENU */

#define IABOUTTX         1   /* Form/Dialog-box */

#define IEDIT            2   /* Form/Dialog-box */
#define IEDDISP          1   /* USERDEF in tree IEDIT */
#define IEDINVIS         2   /* IBOX in tree IEDIT */
#define IEDVBOX          3   /* IBOX in tree IEDIT */
#define IEDVSEL          5   /* BUTTON in tree IEDIT */
#define IEDVPLUS         6   /* BUTTON in tree IEDIT */
#define IEDDSEL          8   /* BUTTON in tree IEDIT */
#define IEDDPLUS         9   /* BUTTON in tree IEDIT */
#define IEDPSEL          11  /* BUTTON in tree IEDIT */
#define IEDPIMG          12  /* IMAGE in tree IEDIT */
#define IPOINT           13  /* ICON in tree IEDIT */
#define ILINE            14  /* ICON in tree IEDIT */
#define IFILL            15  /* ICON in tree IEDIT */
#define IBOX             16  /* ICON in tree IEDIT */
#define IFILBOX          17  /* ICON in tree IEDIT */
#define IEDCBOX          18  /* IBOX in tree IEDIT */
#define IEDCSEL          20  /* BUTTON in tree IEDIT */
#define IEDCPLUS         21  /* BUTTON in tree IEDIT */
#define IEDCOL0          23  /* USERDEF in tree IEDIT */
#define IEDUP            39  /* BUTTON in tree IEDIT */
#define IEDLEFT          40  /* BUTTON in tree IEDIT */
#define IEDRT            41  /* BUTTON in tree IEDIT */
#define IEDDOWN          42  /* BUTTON in tree IEDIT */
#define IEDDBINV         43  /* IBOX in tree IEDIT */
#define IEDDATA          44  /* BUTTON in tree IEDIT */
#define IEDSEL           46  /* BUTTON in tree IEDIT */
#define IEDTBOX          47  /* IBOX in tree IEDIT */
#define IEDTSEL          49  /* BUTTON in tree IEDIT */
#define IEDPLUS          50  /* BUTTON in tree IEDIT */
#define IEDOK            51  /* BUTTON in tree IEDIT */
#define IEDCANC          52  /* BUTTON in tree IEDIT */
#define IEDTEMPL         53  /* FBOXTEXT in tree IEDIT */
#define IEDDESK          54  /* BOX in tree IEDIT */
#define IEDDIC1          55  /* USERDEF in tree IEDIT */
#define IEDWIND          57  /* BOX in tree IEDIT */
#define IEDWIC1          58  /* USERDEF in tree IEDIT */

#define IICON            3   /* Form/Dialog-box */

#define NICINFO          4   /* Form/Dialog-box */
#define NICNAME          3   /* FTEXT in tree NICINFO */
#define NICCREAT         6   /* STRING in tree NICINFO */
#define NICMOD           8   /* STRING in tree NICINFO */
#define NICICONS         10  /* STRING in tree NICINFO */
#define NICAUTH          11  /* FTEXT in tree NICINFO */
#define NICCOMM1         13  /* FTEXT in tree NICINFO */
#define NICOK            17  /* BUTTON in tree NICINFO */

#define IWINMENU         5   /* Menu-tree */
#define IWIMOPEN         6   /* STRING in tree IWINMENU */
#define IWIMSHOW         7   /* STRING in tree IWINMENU */
#define IDELITM          8   /* STRING in tree IWINMENU */
#define ICREATEN         10  /* STRING in tree IWINMENU */
#define ICREATEF         12  /* STRING in tree IWINMENU */
#define ICLSFLD          13  /* STRING in tree IWINMENU */
#define ICLSWIN          14  /* STRING in tree IWINMENU */
#define IEDUPDAT         15  /* STRING in tree IWINMENU */
#define ISELALL          17  /* STRING in tree IWINMENU */

#define ICMENU           6   /* Menu-tree */
#define IEDMASK          4   /* TITLE in tree ICMENU */
#define IEDUNDO          10  /* STRING in tree ICMENU */
#define IEDDELIC         11  /* STRING in tree ICMENU */
#define IEDCLEAR         12  /* STRING in tree ICMENU */
#define IEDDELBO         13  /* STRING in tree ICMENU */
#define IROT             15  /* STRING in tree ICMENU */
#define IHFLIP           16  /* STRING in tree ICMENU */
#define IVFLIP           17  /* STRING in tree ICMENU */
#define IEDDBL           19  /* STRING in tree ICMENU */
#define IEDHALF          20  /* STRING in tree ICMENU */
#define IDELSEL          22  /* STRING in tree ICMENU */
#define IDELREZ          23  /* STRING in tree ICMENU */
#define IEDINTER         25  /* STRING in tree ICMENU */
#define IEDBLUR          26  /* STRING in tree ICMENU */
#define IEDDTOM          27  /* STRING in tree ICMENU */
#define IDRAW            29  /* STRING in tree ICMENU */
#define ICOPY            30  /* STRING in tree ICMENU */
#define IMOVE            31  /* STRING in tree ICMENU */
#define IEDLET           32  /* STRING in tree ICMENU */
#define INONE            34  /* STRING in tree ICMENU */
#define ILR              35  /* STRING in tree ICMENU */
#define ITB              36  /* STRING in tree ICMENU */
#define I4WAY            37  /* STRING in tree ICMENU */
#define IEDCUT           39  /* STRING in tree ICMENU */
#define IEDCOPY          40  /* STRING in tree ICMENU */
#define IEDPASTE         41  /* STRING in tree ICMENU */
#define IEDCUTB          43  /* STRING in tree ICMENU */
#define IEDCOPYB         44  /* STRING in tree ICMENU */
#define IEDPASTB         45  /* STRING in tree ICMENU */

#define IEDPOPS          7   /* Form/Dialog-box */
#define IEDDPAT0         2   /* IMAGE in tree IEDPOPS */
#define IPDATA           19  /* STRING in tree IEDPOPS */
#define IPBOTH           21  /* STRING in tree IEDPOPS */
#define IPFILE           23  /* STRING in tree IEDPOPS */
#define IPSOLID          29  /* IMAGE in tree IEDPOPS */
#define IP2COL           35  /* STRING in tree IEDPOPS */
#define IPSET            39  /* STRING in tree IEDPOPS */
#define IPTOGGLE         41  /* STRING in tree IEDPOPS */
#define IEDPDRIV         42  /* FBOXTEXT in tree IEDPOPS */

#define IFILMENU         8   /* Menu-tree */
#define IFILOPEN         7   /* STRING in tree IFILMENU */
#define IFILDEL          8   /* STRING in tree IFILMENU */
#define ISAVENIC         10  /* STRING in tree IFILMENU */
#define IFILCLS          12  /* STRING in tree IFILMENU */
#define IFILALL          14  /* STRING in tree IFILMENU */
#define IEDNEWIC         16  /* STRING in tree IFILMENU */
#define IDELALL          17  /* STRING in tree IFILMENU */
#define IREORDER         19  /* STRING in tree IFILMENU */
